#!/usr/bin/env bash
# ~/.bash_paths: PATH management

# TODO: Evaluate if this already covers neovim or if we need ./tool_configs/nvim.sh
# Just trying to centralize PATH var management across all tools
# Add personal bin directories to PATH if they exist
[ -d "$HOME/bin" ] && export PATH="$HOME/bin:$PATH"
[ -d "$HOME/.local/bin" ] && export PATH="$HOME/.local/bin:$PATH"