#!/usr/bin/env bash
# ~/.bash_paths: PATH management

# Add personal bin directories to PATH if they exist
[ -d "$HOME/bin" ] && export PATH="$HOME/bin:$PATH"
[ -d "$HOME/.local/bin" ] && export PATH="$HOME/.local/bin:$PATH"